apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${releaseName}
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: prometheus
      version: 15.10.0
      sourceRef:
        kind: HelmRepository
        name: monitoring-repo
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: sample-metrics-app-defaults
      valuesKey: values.yaml
